#######################################
#      Code écrit par Darkin88        #
#                                     #
#######################################


# summon Armor_Stand ~ ~ ~ {Invulnerable:1b,NoGravity:1b,Invisible:1b,Tags:[timer]}

scoreboard players add @e[type=armor_stand,tag=timer] timer 1

execute @e[type=armor_stand,tag=timer,score_timer_min=2400,score_timer=2400] ~ ~ ~ tellraw @a ["",{"text":"\n"},{"text":"--------------------------------","color":"gold"},{"text":"\n"},{"text":"Notre","bold":true,"color":"aqua"},{"text":" Discord","bold":true,"color":"dark_aqua"},{"text":" ","bold":true},{"text":"[","bold":true,"color":"dark_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"ICI","bold":true,"color":"light_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"]","bold":true,"color":"dark_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"\n"},{"text":"--------------------------------","color":"gold"}]
execute @e[type=armor_stand,tag=timer,score_timer_min=4800,score_timer=4800] ~ ~ ~ tellraw @a ["",{"text":"\n"},{"text":"--------------------------------","color":"gold"},{"text":"\n"},{"text":"Notre","bold":true,"color":"aqua"},{"text":" Discord","bold":true,"color":"dark_aqua"},{"text":" ","bold":true},{"text":"[","bold":true,"color":"dark_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"ICI","bold":true,"color":"light_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"]","bold":true,"color":"dark_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"\n"},{"text":"--------------------------------","color":"gold"}]
execute @e[type=armor_stand,tag=timer,score_timer_min=6000,score_timer=6000] ~ ~ ~ function darkin88:main/clearlag
execute @e[type=armor_stand,tag=timer,score_timer_min=7200,score_timer=7200] ~ ~ ~ tellraw @a ["",{"text":"\n"},{"text":"--------------------------------","color":"gold"},{"text":"\n"},{"text":"Notre","bold":true,"color":"aqua"},{"text":" Discord","bold":true,"color":"dark_aqua"},{"text":" ","bold":true},{"text":"[","bold":true,"color":"dark_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"ICI","bold":true,"color":"light_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"]","bold":true,"color":"dark_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"\n"},{"text":"--------------------------------","color":"gold"}]
execute @e[type=armor_stand,tag=timer,score_timer_min=9600,score_timer=9600] ~ ~ ~ tellraw @a ["",{"text":"\n"},{"text":"--------------------------------","color":"gold"},{"text":"\n"},{"text":"Notre","bold":true,"color":"aqua"},{"text":" Discord","bold":true,"color":"dark_aqua"},{"text":" ","bold":true},{"text":"[","bold":true,"color":"dark_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"ICI","bold":true,"color":"light_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"]","bold":true,"color":"dark_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"\n"},{"text":"--------------------------------","color":"gold"}]
execute @e[type=armor_stand,tag=timer,score_timer_min=12001,score_timer=12001] ~ ~ ~ function darkin88:main/clearlag
execute @e[type=armor_stand,tag=timer,score_timer_min=12002,score_timer=12002] ~ ~ ~ tellraw @a ["",{"text":"\n"},{"text":"--------------------------------","color":"gold"},{"text":"\n"},{"text":"Notre","bold":true,"color":"aqua"},{"text":" Discord","bold":true,"color":"dark_aqua"},{"text":" ","bold":true},{"text":"[","bold":true,"color":"dark_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"ICI","bold":true,"color":"light_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"]","bold":true,"color":"dark_purple","clickEvent":{"action":"open_url","value":"https://discord.gg/7eYj7Xn6kP"}},{"text":"\n"},{"text":"--------------------------------","color":"gold"}]
execute @e[type=armor_stand,tag=timer,score_timer_min=12003,score_timer=12003] ~ ~ ~ title @a actionbar {"text":"Vous avez reçu un coins","bold":"true","underlined":"true","color":"yellow"}
execute @e[type=armor_stand,tag=timer,score_timer_min=12004,score_timer=12004] ~ ~ ~ xp 1l @a
execute @e[type=armor_stand,tag=timer,score_timer_min=12003,score_timer=12003] ~ ~ ~ scoreboard players set @e[type=armor_stand,tag=timer] timer 0